MED/Models/Cursos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace MED.Models
{
    [Table("tbl_Programa")]
    public class tbl_Programa
    {
        public int Id_programa { get; set; }
        public string Nombre { get; set; }
        public string NombreEmpleado { get; set; }
        public DateTime FechaInsercion { get; set; }
    }

    [Table("tbl_Curso")]
    public class tbl_Curso
    {
        public int Id_curso { get; set; }
        public int ID { get; set; }
        public int Id_programa { get; set; }
        public int Score { get; set; }
        public int IdExamen { get; set; }
        public string Nombre_Curso { get; set; }
        public string Descripcion { get; set; }
        public string Status { get; set; }
        public string FechaRealizado { get; set; }
        public List<tbl_Archivo> Archivos { get; set; }
        public List<tbl_Curso> Curso { get; set; }
        public int Id_CursoA { get; set; }
        public String Leyenda { get; set; }
    }

    [Table("tbl_Archivo")]
    public class tbl_Archivo
    {
        public int ID { get; set; }
        public int Id_archivo { get; set; }
        public int Id_curso { get; set; }
        public string Nombre_archivo { get; set; }
        public string Ruta { get; set; }
        public string Tipo { get; set; }
        public int Id_examen { get; set; }
        public int IdExamen { get; set; }
        public string Estado { get; set; }
        public int Tiempo { get; set; }
    }

    public class list_Programas
    {
        public List<tbl_Programa> Programas { get; set; }
    }

    public class List_CursosRealizados
    {
        public List<tbl_Curso> CursosRealizados { get; set; }
    }

    public class CursoArchivo
    {
        public int Id_programa { get; set; }
        public int Id_curso { get; set; }
        public string Nombre_Curso { get; set; }
        public string Descripcion { get; set; }
        public List<int> Tiempo { get; set; }
        public List<HttpPostedFileBase> File { get; set; }
        public int TiempoAct { get; set; }
        
        public HttpPostedFileBase Actividad { get; set; }
        public string HostInit { get; set; }
        public int id_tipo_curso { get; set; }
        public string Leyenda { get; set; }
        public int ActividadBit { get; set; }
    }

    public class CursoConArchivos
    {
        public int Id_curso { get; set; }
        public string Nombre_Curso { get; set; }
        public string Nombre_Archivo { get; set; }
        public string Descripcion { get; set; }
        public List<tbl_Archivo> Archivos { get; set; }
        public string Usuario { get; set; }
        public int Estatus { get; set; }
        public List<tbl_Curso> Cursos { get; set; }

    }
  


    public class Tbl_Pregunta
    {
        public string Pregunta { get; set; }
        public string Respuesta { get; set; }
        public int Grupo { get; set; }
        public int IdExamen { get; set; }
        public string Retroalimentacion { get; set; }
    }

    public class Tbl_Respuesta
    {
        public int IdRespuesta { get; set; }
        public string Opcion { get; set; }
        public string Respuesta { get; set; }
        public int Grupo { get; set; }
    }

    public class CursosConCalificacion
    {
        public int IdEvaluacion { get; set; }
        public string NumEmpleado { get; set; }
        public string RFC { get; set; }
        public string NombreCompleto { get; set; }
        public string Puesto { get; set; }
        public string Turno { get; set; }
        public string Supervisor { get; set; }
        public string FechaIngreso { get; set; }
        public string Antiguedad { get; set; }
        public string Campana { get; set; }
        public double Calificacion { get; set; }
        public string FechaCertificado { get; set; }
        public string Aprobado { get; set; }
        public string Curso { get; set; }
        public string Leyenda { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
    }

    public class ListCursos
    {
        public List<tbl_Curso> Cursos { get; set; }
    }

    public class FiltroCursos
    {
        public int IdCurso { get; set; }
        public string FechaInicio { get; set; }
        public string FechaFin { get; set; }
        public string NumEmp { get; set; }
        public string RFC { get; set; }
        public string Nom_curso { get; set; }

    }

    public class cat_tipo_curso
    {
        public int id_tipo_curso { get; set; }
        public string Tipo { get; set; }
    }

    public class List_tipo_curso
    {
        public List<cat_tipo_curso> TipoCursos { get; set; }
    }
}

MED/Controllers/CursoController.cs
using MED.Models;
using System.Web.Mvc;

namespace MED.Controllers
{
    public class CursoController : Controller
    {
        CursosDB obj = new CursosDB();
        // GET: Curso
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AdminProg()
        {
            list_Programas ls = new list_Programas();
            ls.Programas = obj.CargarProgramas();
            ViewData["Programas"] = ls;
            List_tipo_curso lst = new List_tipo_curso();
            lst.TipoCursos = obj.CargarTipoCurso();
            ViewData["TipoCursos"] = lst;
            return View();
        }

        //Vista para asignar los cursos
        public ActionResult AsignarCurso()
        {
            list_Programas ls = new list_Programas();
            ls.Programas = obj.CargarProgramas();
            ViewData["Programas"] = ls;
            return View();
        }

        //Vista para visualizar los cursos asignados
        public ActionResult CursosAsignados()
        {
            return View();
        }

        //Vista para visualizar las calificaciones de los cursos realizados por empleados
        public ActionResult CalificacionesCursos()
        {
            ListCursos ls = new ListCursos();
            ls.Cursos = obj.CargarTotalCursos();
            ViewData["Cursos"] = ls;
            return View();
        }

        public ActionResult Certificado()
        {
            return View();
        }
        
        //Vista para Chrome
        public ActionResult CertificadoC()
        {
            return View();
        }

        public ActionResult BuscarCalifxNumEmp()
        {
            return View();
        }

        //Vista para actualizar fechas 
        public ActionResult ActualizarFechas()
        {
            return View();
        }

        //Vista para asignar cursos de manera masiva
        public ActionResult AsignarCursos_Generadores()
        {
            ListEmpleados ls = new ListEmpleados();
            ls.LstEmp = obj.Lista_AsigarCurso_Generadores();
            ViewData["LstEmp"] = ls;
            return View();
        }

        //Vista para CANYRET
        public ActionResult CANYRET()
        {
            return View();
        }

        public JsonResult CrearPrograma(string nombre,string numEmpleado)
        {
            return Json(obj.CrearPrograma(nombre,numEmpleado), JsonRequestBehavior.AllowGet);
        }

        public JsonResult EliminarPrograma(string idPrograma)
        {
            return Json(obj.EliminarPrograma(idPrograma), JsonRequestBehavior.AllowGet);
        }

        public ActionResult CrearCurso(CursoArchivo curso)
        {
            var id = obj.CrearCurso(curso);
            int contador = 0;
            if (id > 0)
            {
                if (curso.File.Count > 0)
                {
                    for (int i = 0; i < curso.File.Count; i++)
                    {
                        contador = obj.GuardarArchivo(curso.File[i], curso.Nombre_Curso, id,"Contenido",curso.Descripcion,curso.Tiempo[i]);
                    }
                }
                if(curso.Actividad != null)
                {
                    contador = obj.GuardarArchivo(curso.Actividad, curso.Nombre_Curso, id,"Actividad",curso.Descripcion,curso.TiempoAct);
                }
            }
            return Json(contador, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CargarCursos(string idPrograma)
        {
            return Json(obj.CargarCursos(idPrograma), JsonRequestBehavior.AllowGet);
        }

        public JsonResult EditarCurso(CursoArchivo curso)
        {
            var id = obj.ActualizarCurso(curso);
            int contador = 0;
            if (id > 0)
            {
                if (curso.File != null)
                {
                    for (int i = 0; i < curso.File.Count; i++)
                    {
                        contador = obj.GuardarArchivo(curso.File[i], curso.Nombre_Curso, curso.Id_curso,"Contenido",curso.Descripcion,curso.Tiempo[i]);
                    }
                }
                if (curso.Actividad != null)
                {
                    contador = obj.GuardarArchivo(curso.Actividad, curso.Nombre_Curso, curso.Id_curso, "Actividad",curso.Descripcion,curso.TiempoAct);
                    
                }
            }
            return Json(contador == 0 ? id : contador, JsonRequestBehavior.AllowGet);
        }

        public JsonResult EliminarCurso(int idCurso, string nombreCurso)
        {
            return Json(obj.EliminarCurso(idCurso, nombreCurso), JsonRequestBehavior.AllowGet);
        }
        public JsonResult CargarArchivos(int idCurso)
        {
            return Json(obj.CargarArchivos(idCurso), JsonRequestBehavior.AllowGet);
        }

        public JsonResult EliminarArchivoPorId(int idArchivo, string nombreCurso, string nombreArchivo, int idExamen)
        {
            return Json(obj.EliminarArchivo(idArchivo, nombreCurso, nombreArchivo, idExamen), JsonRequestBehavior.AllowGet);

        }

        /////CURSO ASIGNADO
        /////CURSO ASIGNADO
        public JsonResult CargarCursosAsignados(string Usuario, int Id)
        {
            return Json(obj.CargarCursosAsignados(Usuario, Id), JsonRequestBehavior.AllowGet);
        }

        public JsonResult CargarArchivosEstatus(int idCurso, string Usuario)
        {
            return Json(obj.CargarArchivosEstatus(idCurso, Usuario), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GuardarEstatus(string NumEmpleado, int IdArchivo, string EstatusVideo, int ID)
        {
            return Json(obj.GuardarEstatus(NumEmpleado, IdArchivo, EstatusVideo, ID), JsonRequestBehavior.AllowGet);
        }

        public JsonResult Calificar(retro r)
        {
            return Json(obj.Calificar(r), JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateEstatus(int IdVariable, string calificacion)
        {
            return Json(obj.UpdateEstatus(IdVariable, calificacion), JsonRequestBehavior.AllowGet);
        }


        public JsonResult CargarCursosRealizados(string Usuario,int id)
        {
            return Json(obj.CargarCursosRealizados(Usuario,id), JsonRequestBehavior.AllowGet);
        }
        public JsonResult IntentosEvaluacion(int idexamen,string NumEmpleado,string fecha,int ID)
        {
            return Json(obj.IntentosEvaluacion(idexamen, NumEmpleado, fecha, ID), JsonRequestBehavior.AllowGet);
        }

        /////-------------------Asignar curso

        //Cargar los empleados que tengan el id de la direccion seleccionada
        public JsonResult CargarEmp_Direccion(int id)
        {
            return Json(obj.CargarEmp_Direccion(id), JsonRequestBehavior.AllowGet);
        }

        //Carga a los empleados que tengas el id de la direccion y departamento seleccionado
        public JsonResult Cargar_EmpDirecDepart(int id_dir, int id_dep)
        {
            return Json(obj.Cargar_EmpDirecDepart(id_dir, id_dep), JsonRequestBehavior.AllowGet);
        }

        //Carga a los empleados dependiendo de la camapaña que tengan asignadas
        public JsonResult Cargar_EmpCamp(int id_camp)
        {
            return Json(obj.Cargar_EmpCamp(id_camp), JsonRequestBehavior.AllowGet);
        }

        //Trae a un empleado en especifico
        public JsonResult Buscar_Emp(string num_emp)
        {
            return Json(obj.Buscar_Emp(num_emp), JsonRequestBehavior.AllowGet);
        }

        //Cargar los cursos dependiendo del programa
        public JsonResult Cargar_CursosPrograma(int id)
        {
            return Json(obj.Cargar_CursosPrograma(id), JsonRequestBehavior.AllowGet);
        }

        //Manda los datos para asignar el curso
        public JsonResult Asignar_Curso(int id_curso, string id_emp, string capacitador)
        {
            return Json(obj.Asignar_Curso(id_curso, id_emp, capacitador), JsonRequestBehavior.AllowGet);
        }

        //Manda a traer los cursos con sus respectivas calificaciones
        public JsonResult CargarCursosConCalificaciones(FiltroCursos filtro)
        {
            return Json(obj.CargarCursosConCalificacion(filtro), JsonRequestBehavior.AllowGet);
        }
        //Manda a traer los cursos por empleado con sus respectivas calificaciones 
        public JsonResult CargarCursosConCalificacionesxNumEmp(string NumEmp, string RFC)
        {
            return Json(obj.CargarCursosConCalificacionxNumEmp(NumEmp,RFC), JsonRequestBehavior.AllowGet);
        }

        //Buqueda de curso mas reciente aprobado del empleado 
        public JsonResult BuscarCursoxEmpleado(string NumEmp)
        {
            return Json(obj.BusquedaCursoxNumEmp(NumEmp), JsonRequestBehavior.AllowGet);
        }

        //Actualiza Fechas de curso
        public JsonResult ActualizarFechasCursos(FiltroCursos fi)
        {
            return Json(obj.ActualizarFechasCursos(fi), JsonRequestBehavior.AllowGet);
        }
    }

}

MED/Views/Curso/AdminCursos.cshtml
@{
    Layout = null;
}

< <div id="cursos">

    <h3 style="color: steelblue; font: bold; text-align: center;">CURSOS APLICADOS</h3><br />

    <hr />
    <div id="cursosApli" class="row text-center justify-content-center">

    </div>



</div>

MED/Views/Curso/AdminProg.cshtml
@using MED.Models;
@{
    ViewBag.Title = "AdminProg";
}
@{
    var programas = ViewData["Programas"] as list_Programas;
    var tipoCursos = ViewData["TipoCursos"] as List_tipo_curso;
}
<style>
    #agregar:hover {
        opacity: 0.8;
    }
</style>
<div class="container" id="container">
    <div class="row text-center">
        <div class="col-md-12" style="background-color: #17A2B8; border-radius: 5px; padding: 3px; font-size:20px; height: 60px;">
            <div class="col-md-12 text-center" style="color: white;">
                <h1 id="tituloProgramas">Programas</h1>
            </div>
        </div>
    </div>
    <br />
    <div class="row align-items-center justify-content-center">
        <div id="InsEmp" class="col-md-4">
            <button type="button" id="btn_InsEmp" class="btn btn-info" onclick="mostrarModal()"><i class="fas fa-plus-circle" style="color:#fff; padding-right: 8px"></i>Agregar</button>
        </div>
    </div>
    <div class="row justify-content-center align-items-center">

        <div class="col-md-10" style="width:100% !important">
            @{
                if (programas.Programas.Count > 0)
                {
                    <table class=" table table:hover table-striped text-center" style="margin-left:10px; margin-top:10px;">

                        <thead class="tblHead">
                            <tr>
                                <td>Nombre del Programa</td>
                                <td>Empleado</td>
                                <td>Fecha de creación</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < programas.Programas.Count; i++)
                            {
                            <tr>
                                <td >@programas.Programas[i].Nombre</td>
                                <td >@programas.Programas[i].NombreEmpleado</td>
                                <td >@programas.Programas[i].FechaInsercion.ToShortDateString()</td>
                                <td ><button style="padding:7px;" title="Agregar" data-toggle="modal" data-target="#modalCurso" class="btn btn-info" onclick="MostrarModalCurso(@programas.Programas[i].Id_programa)"><i class="fas fa-folder-plus"></i></button></td>
                                <td ><button style="padding:8px;" title="Eliminar" onclick="EliminarPrograma(@programas.Programas[i].Id_programa)" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button></td>
                                <td ><button title="Ver Cursos" class="btn" onclick="CargarCursos(@programas.Programas[i].Id_programa)" style="background:#4682b4; color:white; padding:7px;"><i class="fas fa-eye"></i></button></td>
                            </tr>
                            }
                        </tbody>
                    </table>

                }
            }
        </div>
    </div>
    <div id="cursos" class="row text-center justify-content-center">


    </div>

</div>

<div class="modal fade" id="modalPrograma">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header align-items-center" style="background: #4682b4; color: white; justify-content:center;">
                <h4 class="modal-title" id="title">Crear Programa</h4>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <form id="frmCrearPrograma">
                    <div class="row text-center">
                        <div class="form-group col-md-12">
                            <label> Nombre</label>
                            <input type="text" class="form-control" id="nombre" name="Nombre"/>
                            <input type="hidden" class="form-control" id="numEmpleado" name="NumEmpleado" />
                        </div>
                    </div>
                </form>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer ">
                <button type="submit" class="col-md-2" style="height:40px; padding:0px !important; background:#17b84d !important; border-radius:10px;" onclick="validarCampo()">Guardar</button>
                <button type="button" class="col-md-2 btn btn-danger" data-dismiss="modal" style="height: 40px; padding: 0px !important;border-radius:10px;" onclick="cierraModal()">Cerrar</button>

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalCurso" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered">
        <form action="@Url.Action("CrearCurso","Curso")" method="post" id="frmCrearCurso" enctype="multipart/form-data">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header align-items-center" style="background: #4682b4; color: white; justify-content:center;">
                    <h4 class="modal-title" id="titulo"></h4>
                </div>
                <!-- Modal body -->
                <div class="modal-body">
                    <input type="hidden" id="id_Programa" name="Id_programa" />
                    <input type="hidden" id="id_Curso" name="Id_curso"/>
                    <div class="row text-center justify-content-center">
                        <div class="form-group col-md-7">
                            <label> Nombre</label>
                            <input type="text" class="form-control" id="nombreCurso" name="Nombre_Curso" placeholder="Nombre del curso"/>
                        </div>

                        <div class="form-group col-md-12">
                            <label> Descripcion</label>
                            <input type="text" class="form-control" id="descripcion" name="Descripcion" placeholder="Descripción"/>
                        </div>

                        <div class="form-group col-md-10">
                            <label> Tipo de curso</label>
                            <select id="id_tipo_curso" name="id_tipo_curso" class="form-control">
                                <option value="0" selected>SELECCIONE</option>
                                @for (int i = 0; i < tipoCursos.TipoCursos.Count; i++)
                                {
                                    <option value="@tipoCursos.TipoCursos[i].id_tipo_curso">@tipoCursos.TipoCursos[i].Tipo</option>
                                }
                            </select>
                        </div>

                        <div class="form-group col-md-10">
                            <label>Leyenda en Certificado</label>
                            <textarea id="Leyenda" name="Leyenda" class="form-control" placeholder="Leyenda"></textarea>
                        </div>
                        <div class="form-group col-md-12">
                            <input id="ActividadBit" name="ActividadBit" value="0" hidden/>
                            <label style="margin-right:10px;">¿Tiene actividad?</label>
                            <input type="radio" id="si" name="Excel" onchange="CrearActividad()" value="Si" /> Si
                            <input type="radio" id="no" style="margin-left:15px;" name="Excel" onchange="CrearActividad()" value="No" /> No
                            <div class="row">
                                <div class="form-group col-md-9">
                                    <input type="file" class="form-control" id="Actividad" name="Actividad" hidden accept=".xlsx" />
                                </div>
                                <div class="form-group col-md-3">
                                    <input style="font-size:14px;" type="number" class="form-control" id="TiempoAct"  title="Agrega tiempo en minutos, para el término de la actividad" placeholder="Tiempo" name="TiempoAct" hidden />
                                </div>
                            </div>
                        </div>
                        <div class="row col-md-12" id="divActividad" hidden>
                            
                        </div>

                        <div id="InsEmp" class="col-md-4">
                            <button type="button" id="btn_InsEmp" title="Agregar contenido PDF" onclick="AgregaVistaContenido()" class="btn btn-info"><i class="fas fa-plus-circle" style="color:#fff; padding-right: 5px"></i>Agregar PDF</button>
                        </div>

                        <div id="contenido" class="form-group col-md-12" style="margin-top:10px; margin-right:15px;">

                        </div>
                    </div>

                </div>
                <!-- Modal footer -->
                <div class="modal-footer">
                    
                    <input type="submit" id="agregar" class="col-md-2 btn btn-succes .modal-content" style="height:40px; color:white; padding:0px !important; background:#17b84d !important; border-radius:10px;" value="Guardar" />
                    <button id="cerrarCurso" type="button" class="col-md-2 btn btn-danger" data-dismiss="modal" onclick="LimpiarCampos()" style="height: 40px; padding: 0px !important;border-radius:10px;">Cerrar</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="modalDocumento">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header align-items-center" style="background: #4682b4; color: white; justify-content:center;">
                <h4 class="modal-title" id="TituloDocumento"></h4>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div class="row text-center">
                    <div class="form-group col-md-12" id="divDocumento">
                           
                    </div>
                </div>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <label id="error" style="color:red" class="col-md-10 text-left"></label>
                <button type="button" class="col-md-2 btn btn-danger" data-dismiss="modal" style="height: 40px; padding: 0px !important;border-radius:10px;">Cerrar</button>

            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        Session();
    })

    document.getElementById('frmCrearCurso').onsubmit = function (event) {
        event.preventDefault();
        var vacio = 0;
        var nombre = document.getElementById('nombreCurso').value;
        var idPrograma = document.getElementById("id_Programa").value;
        var actividad = document.getElementById("idActividad");
        let id_tipo_curso = document.getElementById('id_tipo_curso');
        let Leyenda = document.getElementById('Leyenda');

        if (nombre == "") {
            alertify.error("¡Error, debe llenar todos los campos!");
        } else if (id_tipo_curso.value == "0") {
            alertify.error("Se tiene que especificar el tipo de curso")
            id_tipo_curso.focus();
        } else if (Leyenda.value == "") {
            alertify.error("Favor de ingresar la leyenda que aparecera en el certificado de acreditación")
            Leyenda.focus();
        }
        else {
            var inputs = document.getElementsByName('file');
            if (inputs.length == 0) {
                alertify.error("¡Error, el curso debe tener contenido!");
            } else {
                for (var i = 0; i < inputs.length; i++) {
                    if (inputs[i].value == "") {
                        vacio++;
                    }
                }
                if (vacio > 0 || (document.getElementById("Actividad").value == "" && document.getElementById("si").checked == true && actividad == null)) {
                    alertify.error("¡Error, los archivos no pueden ir vacios!");
                }
                else {
                    var msj = "";
                    var error = "";
                    var post_url;
                    var id = document.getElementById("id_Curso").value;
                    if (id != "") {
                        post_url = "/Curso/EditarCurso"
                        msj = "se actualizó el curso correctamente!";
                        error = "no se pudo actualizar el curso!";
                    } else {
                        post_url = $(this).attr("action");
                        msj = "se agrego el curso correctamente";
                        error = "no se pudo crear el curso!";
                    }
                    var request_method = $(this).attr("method");
                    var formData = new FormData(this);

                    $.ajax({
                        url: post_url,
                        type: request_method,
                        data: formData,
                        cache: false,
                        contentType: false,
                        processData: false
                    }).done(function (response) {
                        if (response == 1) {
                            $("#modalCurso").modal("hide");
                            CargarCursos(idPrograma);
                            alertify.success("¡Exitoso, " + msj);
                            LimpiarCampos();
                        }
                        else {
                            alertify.error("¡Error, " + error);
                        }
                    }).fail(function () {
                        $("#modalCurso").modal("hide");
                        alertify.error("¡Error, verifiquelo con el administrador!");
                    });
                }
            }
        }
    }
</script>

MED/Views/Curso/AsignarCursos_Generadores.cshtml
@using MED.Models;
@{
    var emp = ViewData["LstEmp"] as ListEmpleados;
}
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AsignarCursos_Generadores</title>
</head>
<body>
    <div>
        @for (int i = 0; i < emp.LstEmp.Count; i++)
        {
            @*<option value="">@cursos.Cursos[i].Nombre_Curso</option>*@
            <input type="text" class="form-control" value="@emp.LstEmp[i].id_Empleado" id="Id_empleado_G" />
            <br />
        }
        <button type="button" class="btn btn-info" onclick="Traer_Generadores()">Asignar curso</button>
    </div>
    <script>
        //Trae todos los datos para poder mandar a llamar el metodo que asigna curso
        function Traer_Generadores() {
            var id = document.querySelectorAll('input[id="Id_empleado_G"]');
            for (var i = 0; i < id.length; i++) {
                setTimeout(
                    //Encriptar_Pass(id[i].value, clabe[i].value, numcu[i].value), 1000
                    AsignarCurso_Generadores(id[i].value), 1000
                );
                //console.log(id[i].value,clabe[i].value, numcu[i].value);
                // console.log(id[i].value, numEmp[i].value);
            }
            console.log(id);
        }

        //Mandadara los datos para poder ser encriptados
        function AsignarCurso_Generadores(Id_Empleado) {
            var xml = new XMLHttpRequest();
            var url =  "/Curso/Asignar_Curso";
            var json = {
                id_curso: 53,
                id_emp: Id_Empleado,
                capacitador: 709
            }

            xml.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    var r = JSON.parse(this.responseText);
                    console.log(r);
                    if (r == 1) {
                        alertify.success("Curso asignado correctamente");
                        console.log("1");
                    } else if (r = 2) {
                        alertify.alert("Usuario cuenta con mismo curso sin terminar. Favor de terminar el curso antes asignado, antes de asignar uno nuevo");
                        console.log("2");
                    } else {
                        alertify.error("Error al asignar");
                        console.log("3");
                    }
                }
            };
            xml.open("POST", url, true);
            xml.setRequestHeader("Content-Type", "application/json");
            xml.send(JSON.stringify(json));
        }
    </script>
</body>
</html>

MED/Views/Curso/CANYRET.cshtml
<div class="container">
    <div class="row text-center">
        <div class="col-sm-12" style="background-color: #17A2B8; border-radius: 5px; padding: 3px; font-size:20px; height: 60px;">
            <div class="col-sm-12 text-center" style="color: white;">
                <h1>CANYRET</h1>
            </div>
        </div>
    </div>
</div>